In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
data = pd.read_csv("combined.csv")

data["date"] = pd.to_datetime(data["date"], format="%Y-%m-%d %H:%M:%S")
data = data.drop("date.1", axis=1)
data.index = data["date"]

data = data.fillna(0)

data

,date,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
date,,,,,,,,,,
2017-01-01 00:00:00,2017-01-01 00:00:00,4.2,0.0,2.1,320.0,68.0,1021.5,0.0,20000.0,0.0
2017-01-01 01:00:00,2017-01-01 01:00:00,4.1,0.0,1.9,320.0,67.0,1021.4,0.0,20000.0,0.0
2017-01-01 02:00:00,2017-01-01 02:00:00,3.9,0.0,1.0,250.0,68.0,1021.7,0.0,20000.0,0.0
2017-01-01 03:00:00,2017-01-01 03:00:00,3.7,0.0,1.9,320.0,70.0,1021.6,0.0,20000.0,0.0
2017-01-01 04:00:00,2017-01-01 04:00:00,3.6,0.0,1.1,50.0,72.0,1020.7,0.0,17950.0,0.0
...,...,...,...,...,...,...,...,...,...,...
2023-10-18 19:00:00,2023-10-18 19:00:00,18.7,0.0,1.8,180.0,72.0,15.5,2.0,4057.0,0.0
2023-10-18 20:00:00,2023-10-18 20:00:00,16.4,0.0,0.7,200.0,84.0,15.6,3.0,3245.0,0.0
2023-10-18 21:00:00,2023-10-18 21:00:00,14.4,0.0,0.5,70.0,88.0,14.4,6.0,2590.0,0.0
2023-10-18 22:00:00,2023-10-18 22:00:00,13.0,0.0,0.1,0.0,92.0,13.7,5.0,1632.0,0.0
2023-10-18 23:00:00,2023-10-18 23:00:00,12.1,0.0,0.0,0.0,94.0,13.2,6.0,1913.0,0.0

In [25]:
hour_range = np.arange(9, 19)
hour_range

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [26]:
# 활동 시간 중
selected_data = data[data["date"].dt.hour.isin(hour_range)]
selected_data = selected_data.drop("date", axis = 1)
selected_data

,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
date,,,,,,,,,
2017-01-01 09:00:00,3.6,0.0,1.5,230.0,72.0,1022.5,20.0,11230.0,0.15
2017-01-01 10:00:00,5.7,0.0,1.3,200.0,65.0,1022.8,20.0,18210.0,0.63
2017-01-01 11:00:00,6.3,0.0,1.7,90.0,67.0,1022.3,0.0,12830.0,0.94
2017-01-01 12:00:00,8.1,0.0,1.3,160.0,57.0,1021.4,0.0,18670.0,1.29
2017-01-01 13:00:00,8.8,0.0,1.0,110.0,55.0,1020.4,0.0,20000.0,1.41
...,...,...,...,...,...,...,...,...,...
2023-10-18 14:00:00,23.2,0.0,2.0,230.0,46.0,13.0,4.0,5000.0,2.49
2023-10-18 15:00:00,22.8,0.0,1.3,230.0,46.0,12.7,6.0,5000.0,1.93
2023-10-18 16:00:00,22.3,0.0,2.0,180.0,51.0,13.7,6.0,4918.0,1.33
2023-10-18 17:00:00,21.3,0.0,1.1,230.0,51.0,12.9,1.0,5000.0,0.75
2023-10-18 18:00:00,18.1,0.0,1.5,160.0,70.0,14.5,3.0,5000.0,0.12

In [27]:
# 활동 시간에 비가 온 날들
selected_data2 = data[(data["rain"] > 0) & (data["date"].dt.hour.isin(hour_range))]
selected_data2 = selected_data2.drop("date", axis = 1)
selected_data2

,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
date,,,,,,,,,
2017-01-20 15:00:00,1.0,0.1,11.0,320.0,47.0,1012.4,20.0,20000.0,1.14
2017-01-29 09:00:00,5.6,4.2,5.9,90.0,85.0,1011.3,100.0,8350.0,0.04
2017-01-29 12:00:00,6.2,1.8,5.1,70.0,82.0,1009.6,100.0,19130.0,0.20
2017-02-20 12:00:00,8.3,0.2,8.9,340.0,21.0,1002.9,40.0,20000.0,1.11
2017-02-22 09:00:00,5.0,0.9,7.3,70.0,73.0,1011.3,100.0,10860.0,0.06
...,...,...,...,...,...,...,...,...,...
2023-10-03 13:00:00,18.7,0.1,0.5,360.0,77.0,16.5,9.0,3675.0,0.51
2023-10-03 14:00:00,19.5,0.1,1.0,110.0,76.0,17.2,10.0,5000.0,0.76
2023-10-03 16:00:00,17.6,0.6,1.0,360.0,87.0,17.5,9.0,1658.0,0.19
2023-10-03 17:00:00,17.1,0.4,0.9,340.0,91.0,17.7,10.0,2750.0,0.11
2023-10-03 18:00:00,16.4,0.1,0.0,0.0,94.0,17.5,9.0,3193.0,0.03

In [36]:
# 전체 데이터 그대로
pearson_selected_corr0 = data.corr("pearson")

pearson_selected_corr0

,date,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
date,1.000000,0.032506,0.019881,-0.545536,-0.233962,0.118677,-0.857872,-0.496802,-0.754623,0.052659
temperature,0.032506,1.000000,0.067517,0.012211,0.029145,0.269342,0.056060,0.144453,0.043830,0.330986
rain,0.019881,0.067517,1.000000,0.041857,-0.010776,0.159587,-0.009853,0.083037,-0.078247,-0.071690
wind_speed,-0.545536,0.012211,0.041857,1.000000,0.404946,-0.285796,0.621809,0.390942,0.620518,0.115200
wind_direction,-0.233962,0.029145,-0.010776,0.404946,1.000000,-0.390865,0.246165,0.036227,0.262579,0.220819
humidity,0.118677,0.269342,0.159587,-0.285796,-0.390865,1.000000,-0.091973,0.173202,-0.244102,-0.436679
pressure,-0.857872,0.056060,-0.009853,0.621809,0.246165,-0.091973,1.000000,0.598655,0.891922,-0.052571
total_cloud,-0.496802,0.144453,0.083037,0.390942,0.036227,0.173202,0.598655,1.000000,0.464315,-0.156451
visibility,-0.754623,0.043830,-0.078247,0.620518,0.262579,-0.244102,0.891922,0.464315,1.000000,0.023814
solar_radiation,0.052659,0.330986,-0.071690,0.115200,0.220819,-0.436679,-0.052571,-0.156451,0.023814,1.000000

In [29]:
# 전체 데이터에서 비가 온 데이터만 -> 필요없을 듯.
pearson_selected_corr0_1 = data[data["rain"]>0].corr("pearson")
# spearman_selected_corr0_1 = data[data["rain"]>0].corr("spearman")
pearson_selected_corr0_1

,date,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
date,1.000000,0.175266,0.038935,-0.496770,0.040131,0.050494,-0.834838,-0.826538,-0.594635,0.130031
temperature,0.175266,1.000000,0.074189,-0.074018,0.015890,0.250644,-0.067757,-0.065559,-0.004000,0.137362
rain,0.038935,0.074189,1.000000,0.081098,0.060280,0.197333,-0.009945,-0.006670,-0.136754,-0.120429
wind_speed,-0.496770,-0.074018,0.081098,1.000000,0.115513,-0.180255,0.656999,0.655391,0.493703,-0.102788
wind_direction,0.040131,0.015890,0.060280,0.115513,1.000000,-0.152998,-0.035276,-0.042024,-0.000028,0.093651
humidity,0.050494,0.250644,0.197333,-0.180255,-0.152998,1.000000,-0.044839,-0.022261,-0.328255,-0.289429
pressure,-0.834838,-0.067757,-0.009945,0.656999,-0.035276,-0.044839,1.000000,0.992931,0.725892,-0.144385
total_cloud,-0.826538,-0.065559,-0.006670,0.655391,-0.042024,-0.022261,0.992931,1.000000,0.709669,-0.161604
visibility,-0.594635,-0.004000,-0.136754,0.493703,-0.000028,-0.328255,0.725892,0.709669,1.000000,-0.014605
solar_radiation,0.130031,0.137362,-0.120429,-0.102788,0.093651,-0.289429,-0.144385,-0.161604,-0.014605,1.000000

In [30]:
# 9시 ~ 18시
pearson_selected_corr = selected_data.corr("pearson")

pearson_selected_corr

,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
temperature,1.000000,0.033370,-0.104237,-0.090226,0.365056,-0.042383,0.064483,-0.021965,0.353883
rain,0.033370,1.000000,0.009999,-0.046835,0.233649,-0.014277,0.086974,-0.089374,-0.170684
wind_speed,-0.104237,0.009999,1.000000,0.212246,-0.119048,0.615324,0.345023,0.601050,-0.004730
wind_direction,-0.090226,-0.046835,0.212246,1.000000,-0.280673,-0.007055,-0.132820,0.023950,0.128817
humidity,0.365056,0.233649,-0.119048,-0.280673,1.000000,0.074702,0.355245,-0.054107,-0.358911
pressure,-0.042383,-0.014277,0.615324,-0.007055,0.074702,1.000000,0.585977,0.919033,-0.107538
total_cloud,0.064483,0.086974,0.345023,-0.132820,0.355245,0.585977,1.000000,0.471234,-0.325821
visibility,-0.021965,-0.089374,0.601050,0.023950,-0.054107,0.919033,0.471234,1.000000,-0.022103
solar_radiation,0.353883,-0.170684,-0.004730,0.128817,-0.358911,-0.107538,-0.325821,-0.022103,1.000000

In [31]:
# 9~18시 중 비가 온 날만
pearson_selected_corr2 = selected_data2.corr("pearson")
# spearman_selected_corr2 = selected_data2.corr("spearman")

pearson_selected_corr2

,temperature,rain,wind_speed,wind_direction,humidity,pressure,total_cloud,visibility,solar_radiation
temperature,1.000000,0.054971,-0.119735,-0.034923,0.250751,-0.135709,-0.122103,-0.067086,0.239380
rain,0.054971,1.000000,0.048229,0.042134,0.258116,-0.017003,-0.013466,-0.151371,-0.239224
wind_speed,-0.119735,0.048229,1.000000,0.062246,-0.119173,0.640027,0.634854,0.482405,-0.195972
wind_direction,-0.034923,0.042134,0.062246,1.000000,-0.156822,-0.111594,-0.123760,-0.062687,0.077540
humidity,0.250751,0.258116,-0.119173,-0.156822,1.000000,0.016711,0.061259,-0.266306,-0.356916
pressure,-0.135709,-0.017003,0.640027,-0.111594,0.016711,1.000000,0.990892,0.743095,-0.247877
total_cloud,-0.122103,-0.013466,0.634854,-0.123760,0.061259,0.990892,1.000000,0.723838,-0.282752
visibility,-0.067086,-0.151371,0.482405,-0.062687,-0.266306,0.743095,0.723838,1.000000,-0.042224
solar_radiation,0.239380,-0.239224,-0.195972,0.077540,-0.356916,-0.247877,-0.282752,-0.042224,1.000000

In [32]:
# 전체 데이터에 대해
pearson0 = pearson_selected_corr0[(abs(pearson_selected_corr0["solar_radiation"]) >= 0.1) & 
                                  (abs(pearson_selected_corr0["solar_radiation"] < 1))]["solar_radiation"].sort_values(ascending=False)

frame0 = pd.DataFrame()
frame0["Pearson"] = pearson0

frame0

                 Pearson
temperature     0.330986
wind_direction  0.220819
wind_speed      0.115200
total_cloud    -0.156451
humidity       -0.436679

In [37]:
# 전체 데이터에 대해
pearson0 = pearson_selected_corr0[(abs(pearson_selected_corr0["solar_radiation"]) >= 0.2) & 
                                  (abs(pearson_selected_corr0["solar_radiation"] < 1))]["solar_radiation"].sort_values(ascending=False)

frame0 = pd.DataFrame()
frame0["Pearson"] = pearson0

frame0

                 Pearson
temperature     0.330986
wind_direction  0.220819
humidity       -0.436679

In [33]:
# 전체 데이터에서 비가 온 데이터만
pearson0_1 = pearson_selected_corr0_1[(abs(pearson_selected_corr0_1["solar_radiation"]) >= 0.1) & 
                                      (abs(pearson_selected_corr0_1["solar_radiation"] < 1))]["solar_radiation"].sort_values(ascending=False)

frame0_1 = pd.DataFrame()

frame0_1["Pearson"] = pearson0_1

frame0_1

              Pearson
temperature  0.137362
date         0.130031
wind_speed  -0.102788
rain        -0.120429
pressure    -0.144385
total_cloud -0.161604
humidity    -0.289429

In [34]:
# 활동시간 중
pearson = pearson_selected_corr[(abs(pearson_selected_corr["solar_radiation"]) >= 0.1) & 
                                (abs(pearson_selected_corr["solar_radiation"] < 1))]["solar_radiation"].sort_values(ascending=False)

frame = pd.DataFrame()

frame["Pearson"] = pearson

frame

                 Pearson
temperature     0.353883
wind_direction  0.128817
pressure       -0.107538
rain           -0.170684
total_cloud    -0.325821
humidity       -0.358911

In [35]:
# 활동 시간에 비가 온 날들
pearson2 = pearson_selected_corr2[(abs(pearson_selected_corr2["solar_radiation"]) >= 0.1) &  (abs(pearson_selected_corr2["solar_radiation"] < 1))]["solar_radiation"].sort_values(ascending=False)
# spearman2 = spearman_selected_corr2[(abs(spearman_selected_corr2["solar_radiation"]) >= 0.2) &  (abs(spearman_selected_corr2["solar_radiation"] < 1))]["solar_radiation"].sort_values(ascending=False)

frame2 = pd.DataFrame()
frame2["Pearson"] = pearson2
# frame2["Spearman"] = spearman2

frame2

              Pearson
temperature  0.239380
wind_speed  -0.195972
rain        -0.239224
pressure    -0.247877
total_cloud -0.282752
humidity    -0.356916

# 상관도 분석을 통해 판단

## 양의 상관관계
1. 가시성은 실제적으로 가시거리가 멀다는 것으로, 날씨가 좋다는 의미. 즉 일사량을 잘 받을 수 있다는 의미
2. 기온이 높다는 것은 
3. 기압이 높다는 것은 즉 고기압을 의미함. 고기압은 하강기류를 형성하여 공기를 압축하기 때문에 온도가 상승하고, 구름 형성이 억제된다. 즉 맑은 날씨를 보인다.
4. 풍속은 증발량과 양의 상관관계를 가진다. 공기동력학적 방법의 Penman 증발량 산정식에 따르면 풍속이 건조함에 영향을 미치는 요인으로 언급되었다.

## 음의 상관관계
1. 습도